# This is a basic workflow to help you get started with Actions

name: Deploy Hugo

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the gh-pages branch
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
  
      # Check out submodule
      - uses: actions/checkout@v2
        with:
          repository: CaiJimmy/hugo-theme-stack
          path: themes/hugo-theme-stack
          
      - run: ls -a
      
      # Runs a single command using the runners shell
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: latest
          extended: true

      # Runs a set of commands using the runners shell
      - name: Build
        run: hugo --minify
        
      # 复制CNAME
      - name: Copy CNAME
        run: cp ./CNAME ./public/CNAME

      # 发布
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.PAT }} # PAT 这里新建一个 https://github.com/settings/tokens
          PUBLISH_BRANCH: gh-pages  # 推送到当前 gh-pages 分支
          PUBLISH_DIR: ./public  # hugo 生成到 public 作为根目录
          commit_message: ${{ github.event.head_commit.message }}
